### PR TITLE
Decrease visual font size of footnotes

### PR DESCRIPTION
**Pull request by sanssecours**
Hi Bret,

this commit should fix issue #5. If you have any suggestions for changes please just comment below.

Kind regards,
  René

P.S.: Here is a a sample screenshot:

footnote

### CODE REVIEW

**Comment by bcomnes** [comment]
@sanssecours++  Thank you!! Will get this merged in this afternoon.

@amroberts1 What do you think?  Would this be okay?

**Comment by amroberts1** [comment]
Thank you @sanssecours ! This looks great. If it isn't too much work to add, I would be in favor of an additional background color/highlight (preferably encompassing the `\footnote{...}` command and braces too) in order to visually distinguish the footnote even further, analogous to the way code is formatted in the GitHub CSS:

screen shot 2015-03-30 at 1 23 14 pm

Many thanks to both you and @bcomnes for your quick replies.

**Comment by sanssecours** [comment]
> I would be in favor of an additional background color/highlight (preferably encompassing the \footnote{...} command and braces too) in order to visually distinguish the footnote even further, analogous to the way code is formatted in the GitHub CSS

Commit 38c3bec adds a light gray background:

footnote background

Commit 75b9af5 applies the style changes to the whole footnote command:

footnote background whole command

**Comment by bcomnes** [comment]
I like the way 75b9af5 looks.  What do you all think?

**Comment by amroberts1** [comment]
Agreed!

**Comment by bcomnes** [comment]
The background isn't totally noticeable on darker backgrounds, but thats okay with me.  Merging and closes #5.

**Comment by bcomnes** [comment]
@sanssecours What theme are you using?

**Comment by amroberts1** [comment]
Would it be possible to apply this same formatting to the `\footcite{...}` command? (Sorry, I should have mentioned that earlier, but it just occurred to me now.)

**Comment by bcomnes** [comment]
@amroberts1 Same styling?

**Comment by amroberts1** [comment]
@bcomnes Sounds good to me!

**Comment by bcomnes** [comment]
@sanssecours It looks like we have a `meta.citation.latex` selector that also grabs `(?:foot)`.  Is there a way to only select that?

**Comment by sanssecours** [comment]
> What theme are you using?

I use a modified version of “Mac Classic” called [Colorful]( https://github.com/sanssecours/Colorful.tmbundle).

> It looks like we have a meta.citation.latex selector that also grabs (?:foot). Is there a way to only select that to apply the same styling to \footcite{...}?

It looks like cite and footcite have exactly the same scope. To only target `footnote` we need to modify the LaTeX grammar. I will look into it, but it could take some time, since I only did minor grammar changes until now.

**Comment by amroberts1** [comment]
One thought would be to make all citation commands (`\footcite`, `\cite`, `\Cite`, `\volcite`, `\Volcite`, etc.) keep their present formatting except adding the same background as was added to the `\footnote`. In contrast to the `\footnote` argument, the `\footcite` argument (at least in my documents) is invariably short and easily distinguished from the main text, since it is mostly cite-key(s); the gray background, I think, is all that would be needed to visually scan a document and immediately see all the footnotes/citations. If the gray background seems undesirable for other citation commands, then it seems all right to leave it for now without it, unless there is a straightforward way to modify only `\footcite`'s formatting.

**Comment by sanssecours** [comment]
> One thought would be to make all citation commands (\footcite, \cite, \Cite, \volcite, \Volcite, etc.) keep their present formatting except adding the same background as was added to the \footnote. In contrast to the \footnote argument, the \footcite argument (at least in my documents) is invariably short and easily distinguished from the main text, since it is mostly cite-key(s); the gray background, I think, is all that would be needed to visually scan a document and immediately see all the footnotes/citations.

Pull request #7 adds this behaviour.

> If the gray background seems undesirable for other citation commands, then it seems all right to leave it for now without it,…

I see no problem with the gray background for citations. In the end it is Bret's call if he wants to accept the changes or not.

>  …unless there is a straightforward way to modify only \footcite's formatting.

In the moment there is none, but I think changing the grammar for this purpose should not be that hard.

**Comment by bcomnes** [comment]
I'm pretty open to what goes into this. #7 looks good to me.

**Pull request merged**
